### ISSUE TITLE
实现 sharelatex 在线编辑支持

### ISSUE THREAD

**Issue by gaocegege** [dyweb/SJTUThesis#4]
ref https://github.com/weijianwen/SJTUThesis/issues/182

**Comment by at15** [comment]
以前还要同时考虑 sharelatex 和 overleaf ... 现在 /w\

**Comment by gaocegege** [comment]
被买了的没有人权

**Comment by gaocegege** [comment]
婶婶要不要解决几个 issue 啊

**Comment by at15** [comment]
我可以去看看改改 math 的部分.... 当时我主要改的也是那个部分，另外我们要考虑对英文版的支持么?

**Comment by gaocegege** [comment]
当然考虑, 但是不知道是一个新的 repo 还是一个 branch 还是怎样

**Comment by gaocegege** [comment]
编译时选择中英文好像比较难

**Comment by gaocegege** [comment]
我甚至想学士学位模板是不是要单独一个 branch, 因为有很大不同

**Comment by at15** [comment]
可能可以共用一些文件然后用不同的 tex 文件? 我不造 latex 里怎么复用.....

````
share.cls
单身.tex
single-en.tex
master.tex
phd.tex
````

**Comment by gaocegege** [comment]
overleaf 有 50 M 限制

**Comment by gaocegege** [comment]
这也可以吧

**Comment by gaocegege** [comment]
https://cn.sharelatex.com/project/5a03f5e84deb750e5512ccff

**Comment by gaocegege** [comment]
还是 TM 的 sharelatex 好用

**Comment by gaocegege** [comment]
Template: https://www.sharelatex.com/templates/5a03fcddc4aab43a4a6226e2

**Comment by gaocegege** [comment]
overleaf 是什么, 不知道

**Comment by gaocegege** [comment]
sharelatex 已经支持了: #7
